config/routes.rb
Rails.application.routes.draw do
  get '/followers', to: 'followers#index', as: 'show_follower'
  get '/search', to: 'home#search', as: 'search_user'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
require 'net/http'
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  def get_element(link)
    uri = URI(link)
    result = Net::HTTP.get(uri)
  end
  
  def get_follower_list(link)
    uri = URI(link)
    result = Net::HTTP.get(uri)
  end
  
  def get_user_profile_page(username)
    uri = URI("https://github.com/#{username}")
    html_data = Net::HTTP.get_response(uri).body
    follower_num = html_data.match(/Follower(.|\n)*?span>/).to_s.match(/>(.|\n)*?</).to_s.delete('> <')
  end
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  def index
    @next_button = false
    @last_button = false
    @current_page = params[:page_num].to_i
    @link = params[:link]
    @followers = JSON.parse(page_num(@current_page))
    next_page_list = JSON.parse(page_num(@current_page + 1))
    
    @next_button = true if next_page_list.length > 0
    @last_button = true if @current_page - 1 > 0
    
    respond_to do |format|
      format.js
    end
  end
  
  private
  
    def page_num(num)
      get_follower_list("#{@link}?page=#{num}")
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def search
    info = JSON.parse(get_element("https://api.github.com/search/users?q=#{params[:q]}"))
    
    if info.has_key?("message") || info["total_count"] === 0
      @user = 0
    else
      for i in 0...(info['items'].length)
        if(info['items'][i]['login'] === params[:q])
          @user = info['items'][i]
          break
        end
      end
      
      if(@user === nil)
        @user = 0
      else
        @user['following_url'].chomp!("{/other_user}")
        @user["total_follower"] = get_user_profile_page(params[:q])
        @followers = JSON.parse(get_follower_list("https://api.github.com/users/#{params[:q]}/followers"))
        @following = JSON.parse(get_follower_list("https://api.github.com/users/#{params[:q]}/following"))
      end
    end
    
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/followers/_followers.html.erb
<div class='row next_last_btn_area'>
  <% if @last_button %>    
    <div class='col-sm-3'>
      <%= form_tag(show_follower_path, remote: true, method: "get") do %>
        <%= hidden_field_tag :page_num, @current_page - 1 %>
        <%= hidden_field_tag :link, @link %>
        <%= submit_tag("Last Page") %>
      <% end %>
    </div>
  <% end %> 
  <% if @next_button %>
    <div class='col-sm-3'>
      <%= form_tag(show_follower_path, remote: true, method: "get") do %>
        <%= hidden_field_tag :page_num, @current_page + 1 %>
        <%= hidden_field_tag :link, @link %>
        <%= submit_tag("Next Page") %>
      <% end %>
    </div>
  <% end %>
</div>

<div class='row follower_show'>
  <% @followers.each do |follower| %>
    <%= render partial: "show", locals: {follower: follower} %>
  <% end %>
</div>

app/views/followers/_show.html.erb
<div class='col-md-3 follower_info'>
  <div class='row'>
    <% if follower['avatar_url'] %>
      <%= image_tag(follower['avatar_url'], class: "img-responsive", size: '285') %>
    <% else %>
      <%= image_tag('http://www.dejay.co.za/wp-content/uploads/2016/03/noimg.gif', class: "img-responsive", size: '285') %>
    <% end %>
  </div>
  <h3><%= follower['login'] %></h3>
  <%= link_to "GitHub Profile Link", follower['html_url'] %>
</div>

app/views/followers/index.js.erb
$('#follower_area').html('')
$('#follower_area').append("<%= j(render partial: 'followers') %>")

app/views/home/_button.html.erb
<%= form_tag(show_follower_path, remote: true, method: 'get') do %>
  <%= hidden_field_tag :page_num, 1 %>
  <%= hidden_field_tag :link, link %>
  <%= submit_tag(submit_btn_title, class: class_name, id: submit_btn_id) %>
<% end %>

app/views/home/_user.html.erb
<% if @user === 0 %>
  <div class='row'>
    <h2 id='error_message' class='col-md-6 col-md-offset-3'>Please enter a valid username</h2>
  </div>
<% else %>
  <div class='row user_info'>
    <div class='col-md-6 img_area'>
      <% if @user['avatar_url'] %>
        <%= image_tag(@user['avatar_url'], class: "img-thumbnail", size: '360') %>
      <% else %>
        <%= image_tag('http://www.dejay.co.za/wp-content/uploads/2016/03/noimg.gif', class: "img-thumbnail", size: '360') %>
      <% end %>
    </div>
    
    <div class='col-md-6 user_data'>
      <h4>Username: <%= @user['login'] %></h4>
      <h4>GitHub ID: <%= @user['id'] %></h4>
      <h4>Gravatar ID: <%= @user['gravatar_id '] === nil ? "No Gravatar ID" : @user['gravatar_id '] %> </h4>
      <h4><%= link_to "GitHub API Search Link", @user['url'] %></h4>
      <h4><%= link_to "GitHub Profile Link", @user['html_url'] %></h4>
      <h4><%= link_to "Subscriptions Link", @user['subscriptions_url'] %></h4>
      <h4><%= link_to "Organizations Link", @user['organizations_url'] %></h4>
      <h4><%= link_to "Repos Link", @user['repos_url'] %></h4>
      <h4><%= link_to "Received Events Link", @user['received_events_url'] %></h4>
      <h4>User Type: <%= @user['type'] %></h4>
      <h4>A Site Admin? : <%= @user['site_admin'] ? 'YES' : 'NO' %></h4>
      <h4>Score: <%= @user['score'] %></h4>
    </div>
  </div>
  
  <% if @followers.size > 0 || @following.size > 0 %>
    <div class='row follower_following_button'>
      <div class='col-md-12'>
        <h3>Total Follower: <%= @user["total_follower"] %></h3>
      </div>
      
      <div id='follower_btn_area' class='col-md-12'>
        <% if(@followers.size > 0) %>
          <%= render partial: "button", locals: {submit_btn_title: 'Show Follower', submit_btn_id: 'follower_btn', link: @user['followers_url'], class_name: 'btn btn-info'} %>
        <% end %>
        <% if(@following.size > 0) %>
          <%= render partial: "button", locals: {submit_btn_title: 'Show Following', submit_btn_id: 'following_btn', link: @user['following_url'], class_name: 'btn btn-warning'} %>
        <% end %>
      </div>
    </div>
    
    <div id='follower_area'></div>
  <% else %>
    <div class='row'>
      <h2 id='error_message' class='col-md-6 col-md-offset-3 text-center'>This user doesn't have any followers</h2>
    </div>
  <% end %>
<% end %>

app/views/home/index.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to 'GitHub User Search Engine', root_path, class: "navbar-brand" %>
    </div>
  </div>
</nav>
<div class='container main_area'>
  <div class='row text-center'>
    <h4>Search GitHub user by enter their username</h4>
    <%= form_tag(search_user_path, remote: true, method: "get") do %>
      <%= label_tag(:q, "Username:") %>
      <%= text_field_tag(:q) %>
      <%= submit_tag("Search", class: 'btn btn-primary btn-sm') %>
    <% end %>
  </div>
  
  <div id='user_area'></div>
</div>

app/views/home/search.js.erb
$('#q')[0].value = ''
$('#follower_area').html('')
$('#user_area').html('')
$('#user_area').append("<%= j(render partial: 'user') %>")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GetGitHubUser</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>